"""GENERATED projection of ggen/biblegym-pack/ontology.ttl. Do not hand-edit."""
from __future__ import annotations
from .compat import Capability, Consequence
BIBLEGYM_CAPABILITIES: tuple[Capability, ...] = (
    Capability(iri="urn:biblegym:capability:dashboard", title="Read a principal-scoped church dashboard. Payload: {'actor_id': str}.", consequence=Consequence.READ, binding="dashboard"),
    Capability(iri="urn:biblegym:capability:leaderboard", title="Read opt-in quest leaderboard. Payload: {}.", consequence=Consequence.READ, binding="leaderboard"),
    Capability(iri="urn:biblegym:capability:milestones", title="Read a person's milestones. Payload: {'person_id': str}.", consequence=Consequence.READ, binding="milestones"),
    Capability(iri="urn:biblegym:capability:offline_content", title="Read content metadata for offline sync. Payload: {}.", consequence=Consequence.READ, binding="offline_content"),
    Capability(iri="urn:biblegym:capability:devotion_prompt_packet", title="Read a bounded sermon/scripture packet for an external planner or LLM to compose a devotion. Payload: {'person_id': str}.", consequence=Consequence.READ, binding="devotion_prompt_packet"),
    Capability(iri="urn:biblegym:capability:staffing_health", title="Read service staffing requirements, vacancies, no-shows and escalations. Payload: {'event_id': str|optional}.", consequence=Consequence.READ, binding="staffing_health"),
    Capability(iri="urn:biblegym:capability:service_route", title="Read a need-to-follow-up service route. Payload: {'route_id': str}.", consequence=Consequence.READ, binding="service_route"),
    Capability(iri="urn:biblegym:capability:content_sync_manifest", title="Read the offline content-sync manifest, including note/offline metadata. Payload: {}.", consequence=Consequence.READ, binding="content_sync_manifest"),
    Capability(iri="urn:biblegym:capability:register_person", title="Register a person profile with locale, auth assurance and consent preferences.", consequence=Consequence.DO, binding="register_person"),
    Capability(iri="urn:biblegym:capability:create_group", title="Create a small group/accountability community.", consequence=Consequence.DO, binding="create_group"),
    Capability(iri="urn:biblegym:capability:set_next_step", title="Set or complete a person-scoped Next Step without widening it into an unbounded life plan.", consequence=Consequence.DO, binding="set_next_step"),
    Capability(iri="urn:biblegym:capability:join_group", title="Join a person to a group.", consequence=Consequence.DO, binding="join_group"),
    Capability(iri="urn:biblegym:capability:host_autonomous_group", title="Record a church facility-hosting agreement while preserving the hosted group's autonomy and non-ownership boundary.", consequence=Consequence.DO, binding="host_autonomous_group"),
    Capability(iri="urn:biblegym:capability:create_event", title="Create a church event/service with an optional required-volunteer count.", consequence=Consequence.DO, binding="create_event"),
    Capability(iri="urn:biblegym:capability:rsvp_event", title="One-tap RSVP using an existing profile.", consequence=Consequence.DO, binding="rsvp_event"),
    Capability(iri="urn:biblegym:capability:check_in", title="One-tap attendance or volunteer check-in.", consequence=Consequence.DO, binding="check_in"),
    Capability(iri="urn:biblegym:capability:location_check_in", title="Consent-gated campus geofence check-in; precise coordinates are not stored.", consequence=Consequence.DO, binding="location_check_in"),
    Capability(iri="urn:biblegym:capability:qr_check_in", title="One-tap QR event check-in using an opaque event reference; no raw QR secret is persisted.", consequence=Consequence.DO, binding="qr_check_in"),
    Capability(iri="urn:biblegym:capability:child_check_in", title="Guardian-authorized child check-in with hashed pickup token.", consequence=Consequence.DO, binding="child_check_in"),
    Capability(iri="urn:biblegym:capability:publish_content", title="Publish sermon/media/notes metadata, including offline availability.", consequence=Consequence.DO, binding="publish_content"),
    Capability(iri="urn:biblegym:capability:record_content_note", title="Record an encrypted/client-owned sermon-note reference and digest; raw note text is not stored.", consequence=Consequence.DO, binding="record_content_note"),
    Capability(iri="urn:biblegym:capability:schedule_reminder", title="Schedule a bounded reminder intent; no external delivery occurs inside BibleGym.", consequence=Consequence.DO, binding="schedule_reminder"),
    Capability(iri="urn:biblegym:capability:share_invite", title="Create a one-click share intent for an event/group/content item.", consequence=Consequence.DO, binding="share_invite"),
    Capability(iri="urn:biblegym:capability:message_intent", title="Create a template-backed messaging intent; BibleGym does not deliver the message or store a freeform body.", consequence=Consequence.DO, binding="message_intent"),
    Capability(iri="urn:biblegym:capability:contact_intent", title="Create a call/text/email contact shortcut intent; device contact actuation remains external.", consequence=Consequence.DO, binding="contact_intent"),
    Capability(iri="urn:biblegym:capability:record_giving_intent", title="Record a giving intent in minor currency units; no payment instrument is stored or charged.", consequence=Consequence.DO, binding="record_giving_intent"),
    Capability(iri="urn:biblegym:capability:publish_sermon", title="Publish a sermon source with scripture references.", consequence=Consequence.DO, binding="publish_sermon"),
    Capability(iri="urn:biblegym:capability:create_quest_from_sermon", title="Project a sermon point into a scripture-linked small daily quest.", consequence=Consequence.DO, binding="create_quest_from_sermon"),
    Capability(iri="urn:biblegym:capability:complete_quest", title="Record quest completion and derive points, badges and milestones.", consequence=Consequence.DO, binding="complete_quest"),
    Capability(iri="urn:biblegym:capability:set_habit_stack", title="Set an after-existing-routine -> small-practice habit stack, including two-minute practices.", consequence=Consequence.DO, binding="set_habit_stack"),
    Capability(iri="urn:biblegym:capability:link_accountability", title="Link accountability partners with bilateral consent.", consequence=Consequence.DO, binding="link_accountability"),
    Capability(iri="urn:biblegym:capability:submit_scripture_quiz", title="Submit scripture-quiz result tied to an explicit scripture reference.", consequence=Consequence.DO, binding="submit_scripture_quiz"),
    Capability(iri="urn:biblegym:capability:recruit_volunteer", title="Enter a volunteer candidate into a visible recruitment lifecycle.", consequence=Consequence.DO, binding="recruit_volunteer"),
    Capability(iri="urn:biblegym:capability:onboard_volunteer", title="Advance a volunteer candidate to onboarded after explicit readiness checks.", consequence=Consequence.DO, binding="onboard_volunteer"),
    Capability(iri="urn:biblegym:capability:assign_volunteer", title="Assign an onboarded volunteer to a service route/role.", consequence=Consequence.DO, binding="assign_volunteer"),
    Capability(iri="urn:biblegym:capability:assign_cochair", title="Assign an onboarded volunteer as a co-chair/team lead for a ministry route.", consequence=Consequence.DO, binding="assign_cochair"),
    Capability(iri="urn:biblegym:capability:opt_out_volunteer", title="Record a volunteer opt-out and release active assignments without further notification intent.", consequence=Consequence.DO, binding="opt_out_volunteer"),
    Capability(iri="urn:biblegym:capability:record_no_show", title="Record a volunteer no-show and open an explicit staffing gap.", consequence=Consequence.DO, binding="record_no_show"),
    Capability(iri="urn:biblegym:capability:escalate_staffing_gap", title="Escalate an open staffing gap to a named governance route.", consequence=Consequence.DO, binding="escalate_staffing_gap"),
    Capability(iri="urn:biblegym:capability:create_service_route", title="Create need -> route -> door -> role -> assignment -> evidence -> receipt -> follow-up linkage.", consequence=Consequence.DO, binding="create_service_route"),
    Capability(iri="urn:biblegym:capability:route_bible_need", title="Route a bounded Bible/scripture need to content, group, mentor or pastoral care without storing a private narrative.", consequence=Consequence.DO, binding="route_bible_need"),
    Capability(iri="urn:biblegym:capability:record_follow_up", title="Record a bounded follow-up outcome against a person/service route.", consequence=Consequence.DO, binding="record_follow_up"),
    Capability(iri="urn:biblegym:capability:record_prayer_request", title="Record a privacy-minimized prayer request category and consent, never raw private prayer text.", consequence=Consequence.DO, binding="record_prayer_request"),
    Capability(iri="urn:biblegym:capability:record_biometric_assertion", title="Record only a platform biometric-verification assertion; biometric material never enters BibleGym.", consequence=Consequence.DO, binding="record_biometric_assertion"),
    Capability(iri="urn:biblegym:capability:record_formation_step", title="Record only bounded formation metadata and a next faithful action; raw confession detail is refused.", consequence=Consequence.DO, binding="record_formation_step"),
    Capability(iri="urn:biblegym:capability:grant_feedback_consent", title="Grant or revoke consent for feedback/cross-talk from a named person/group.", consequence=Consequence.DO, binding="grant_feedback_consent"),
    Capability(iri="urn:biblegym:capability:record_care_handoff", title="Record a privacy-minimized pastoral/professional/safety routing handoff.", consequence=Consequence.DO, binding="record_care_handoff"),
)
CAPABILITY_BY_BINDING = {c.binding: c for c in BIBLEGYM_CAPABILITIES}
